evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }

ajout:
    path:     /ajout
    defaults: { _controller: EvenementBundle:Evenements:ajout }

mod:
    path:     /modifier/{id}
    defaults: { _controller: EvenementBundle:Evenements:modifier }

s:
    path:     /supprimer/{id}
    defaults: { _controller: EvenementBundle:Evenements:Supprimer }

aff:
    path:     /affichage
    defaults: { _controller: EvenementBundle:Evenements:affiche }


detail:
    path:     /detail/{id}
    defaults: { _controller: EvenementBundle:Evenements:detail }

event:
    path:     /mevent
    defaults: { _controller: EvenementBundle:Evenements:mesevent }
    options:
     expose : true

_ajout:
    path:     /Ajout
    defaults: { _controller: EvenementBundle:CommentaireE:Ajout }

Vote:
    path:     /Vote
    defaults: { _controller: EvenementBundle:Evenements:Vote }

_modifier:
    path:     /Modifier/{id}/{ide}
    defaults: { _controller: EvenementBundle:CommentaireE:Modifier }

_afficher:
    path:     /Afficher
    defaults: { _controller: EvenementBundle:CommentaireE:Afficher }
