evenement_homepage:
    path:     /
    defaults: { _controller: EvenementBundle:Default:index }

ajout:
    path:     /ajout
    defaults: { _controller: EvenementBundle:Evenements:ajout }

modifier:
    path:     /modifier/{id}
    defaults: { _controller: EvenementBundle:Evenements:modifier }

supprimer:
    path:     /supprimer/{id}
    defaults: { _controller: EvenementBundle:Evenements:Supprimer }

aff:
    path:     /affichage
    defaults: { _controller: EvenementBundle:Evenements:affiche }

detail:
    path:     /detail/{id}
    defaults: { _controller: EvenementBundle:Evenements:detail }

afficheu:
    path:     /calendar
    defaults: { _controller: EvenementBundle:Evenements:calendar }
    options:
     expose : true
