blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

entite:
    resource: "@EntiteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
