profil:
    resource: "@ProfilBundle/Resources/config/routing.yml"
    prefix:   /profil

app:
    resource: '@AppBundle/Controller/'
    type: annotation
blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog
evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /evenement

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
entite:
    resource: "@EntiteBundle/Resources/config/routing.yml"
    prefix:   /entite
