<<<<<<< HEAD
app:
    resource: '@AppBundle/Controller/'
    type: annotation

profil:
    resource: "@ProfilBundle/Resources/config/routing.yml"
    prefix:   /

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

=======
exp_avis:
    resource: "@ExpAvisBundle/Resources/config/routing.yml"
    prefix:   /

reservation:
    resource: "@ReservationBundle/Resources/config/routing.yml"
    prefix:   /

map:
    resource: "@MapBundle/Resources/config/routing.yml"
    prefix:   /

profil:
    resource: "@ProfilBundle/Resources/config/routing.yml"
    prefix:   /profil

app:
    resource: '@AppBundle/Controller/'
    type: annotation
blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog
>>>>>>> c0eb860592aaedf60415d0128cb1c40aeb81a18a
evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /evenement

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
<<<<<<< HEAD

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"

=======
>>>>>>> c0eb860592aaedf60415d0128cb1c40aeb81a18a
entite:
    resource: "@EntiteBundle/Resources/config/routing.yml"
    prefix:   /entite
