blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog
evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
entite:
    resource: "@EntiteBundle/Resources/config/routing.yml"
    prefix:   /
