ajouter_etab:
    path:     /profile/etablissement/ajouter
    defaults: { _controller: ProfilBundle:Etablissement:ajouter }
list_etab:
    path:     /etablissement/list
    defaults: { _controller: ProfilBundle:Etablissement:listAll }
best_etab:
    path:     /
    defaults: { _controller: ProfilBundle:Etablissement:all }
cafe_etab:
    path:     /cafes
    defaults: { _controller: ProfilBundle:Etablissement:listCafe }
shop_etab:
    path:     /shops
    defaults: { _controller: ProfilBundle:Etablissement:listShop }
rest_etab:
    path:     /restaurants
    defaults: { _controller: ProfilBundle:Etablissement:listRestaurant }
loisir_etab:
    path:     /loisirs
    defaults: { _controller: ProfilBundle:Etablissement:listLoisir }
supprimer_etab:
    path:     /etablissement/supprimer/{idDelete}
    defaults: { _controller: ProfilBundle:Etablissement:supprimer }
modifier_etab:
    path:     /etablissement/modifier/{idUpdate}
    defaults: { _controller: ProfilBundle:Etablissement:modifier }


ajouter_photo:
    path:     /photo/ajouter
    defaults: { _controller: ProfilBundle:Photo:ajouter }

supprimer_photo:
    path:     /photo/supprimer
    defaults: { _controller: ProfilBundle:Photo:supprimer }

list_photo:
    path:     /photo/list
    defaults: { _controller: ProfilBundle:Photo:list }

modifier_photo:
    path:     photo/modifier
    defaults: { _controller: ProfilBundle:Photo:modifier }

ajouter_utilisateur:
    path:     /utilisateur/ajouter
    defaults: { _controller: ProfilBundle:Utilisateur:ajouter }

supprimer_utilisateur:
    path:     /utilisateur/supprimer/{idDelete}
    defaults: { _controller: ProfilBundle:Utilisateur:supprimer }

modifier_utilisateur:
    path:     /utilisateur/modifier/{idUpdate}
    defaults: { _controller: ProfilBundle:Utilisateur:modifier }

list_utilisateur:
    path:     /utilisateur/list
    defaults: { _controller: ProfilBundle:Utilisateur:list }
all_Json_utilisateur:
    path:     /utilisateur/alljson
    defaults: { _controller: ProfilBundle:Utilisateur:all }
search_etab_param:
    path:     /etablissement/searchDQL/{etab}
    defaults: { _controller: ParcBundle:Modele:rechercheDQLParametre }
all_gouvernorat:
    path:     /gouvernorat/all
    defaults: { _controller: ProfilBundle:Gouvernorat:all }

all_Json_gouvernorat:
    path:     /gouvernorat/alljson
    defaults: { _controller: ProfilBundle:Gouvernorat:alljson }
all_Json_ville:
    path:     /ville/alljson
    defaults: { _controller: ProfilBundle:Ville:alljson }
alljson_etab:
    path:     /etablissement/alljson
    defaults: { _controller: ProfilBundle:Etablissement:alljson }
search_etab:
    path:     /search
    defaults: { _controller: ProfilBundle:Etablissement:rechercheAjax }