profil_homepage:
    path:     /
    defaults: { _controller: ProfilBundle:Default:index }
ajouter_etab:
    path:     /etablissement/ajouter
    defaults: { _controller: ProfilBundle:Etablissement:ajouter }
list_etab:
    path:     /etablissement/list
    defaults: { _controller: ProfilBundle:Etablissement:list }
supprimer_etab:
    path:     /etablissement/supprimer/{idDelete}
    defaults: { _controller: ProfilBundle:Etablissement:supprimer }
modifier_etab:
    path:     /etablissement/modifier/{idUpdate}
    defaults: { _controller: ProfilBundle:Etablissement:modifier }


ajouter_photo:
    path:     /photo/ajouter
    defaults: { _controller: ProfilBundle:Photo:ajouter }

supprimer_photo:
    path:     /photo/supprimer
    defaults: { _controller: ProfilBundle:Photo:supprimer }

list_photo:
    path:     /photo/list
    defaults: { _controller: ProfilBundle:Photo:list }

modifier_photo:
    path:     photo/modifier
    defaults: { _controller: ProfilBundle:Photo:modifier }

ajouter:
    path:     /utilisateur/ajouter
    defaults: { _controller: ProfilBundle:Utilisateur:ajouter }

supprimer:
    path:     /utilisateur/supprimer
    defaults: { _controller: ProfilBundle:Utilisateur:supprimer }

modifier:
    path:     /utilisateur/modifier
    defaults: { _controller: ProfilBundle:Utilisateur:modifier }

list:
    path:     /utilisateur/list
    defaults: { _controller: ProfilBundle:Utilisateur:list }
