profil_homepage:
    path:     /
    defaults: { _controller: ProfilBundle:Default:index }
ajouter:
    path:     /etablissement/ajouter
    defaults: { _controller: ProfilBundle:Etablissement:ajouter }
list:
    path:     /etablissement/list
    defaults: { _controller: ProfilBundle:Etablissement:list }

